#!/bin/bash

echo "pull repository" && git pull && 
echo "populating file" && git add . &&
echo "commit  changes" && git commit -m "$(date)" &&
echo "push to gitrepo" && git push
echo "push to subtree" && git subtree push --prefix=library library main