#!/bin/bash

PACKAGE="${PACKAGE} perl-image-exiftool easytag paper-clip vlc cups darktable ffmpeg kodi-gless docker "
AURPACK="${AURPACK} plattenalbum "
FLATPAK=(  )
RDAEMON="${RDAEMON} docker.service "
GDAEMON="${GDAEMON}"


## CONFIGS
if [[ -d "$appdir/distros/config" ]]; then
    cp -fr "$appdir/distros/config/"* "$appdir/config/define/"
fi