#!/bin/bash

PACKAGE="${PACKAGE} "
AURPACK="${AURPACK} "
FLATPAK=(  )
RDAEMON="${RDAEMON}  "
GDAEMON="${GDAEMON}"


## CONFIGS
if [[ -d "$appdir/distros/config" ]]; then
    cp -fr "$appdir/distros/config/"* "$appdir/config/define/"
fi